sudo: required
language:
- bash
script:
- sudo apt-get install shellcheck
- shellcheck *.sh
- ( cd tests/ && openssl aes-256-cbc -K $encrypted_e3ddca67c2d3_key -iv $encrypted_e3ddca67c2d3_iv -in private-cookies.txt.enc -out private-cookies.txt -d ; )
- ./tests/tests.sh
